name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
 dotnetVersion: '8.0'
        
permissions:
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET ${{ env.dotnetVersion }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.dotnetVersion }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build for ${{ env.dotnetVersion }}
      run: dotnet build --configuration Release --framework net${{ env.dotnetVersion }}

    - name: Publish for ${{ matrix.dotnet-version }}
      run: dotnet publish --configuration Release --framework net${{ env.dotnetVersion }} -o release
    
    - name: Create the package
      run: dotnet pack --configuration Release
    
    - name: Upload artifact for ${{ matrix.dotnet-version }}
      uses: actions/upload-artifact@v4
      with:
        name: published-artifact-net
        path: release

    - name: Show directory
      run: |
        pwd
        ls -al -R
    
  artifact-work:
    runs-on: ubuntu-latest
    steps:
    - name: download artifact 
      uses: actions/download-artifact@v4
      with:
        name: published-artifact-net
        #path: release
                
    - name: Show directory
      run: |
        pwd
        ls -al -R

       
      